version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: openjdk:21-jdk-slim  # Chạy trực tiếp với JDK, không cần build image
    container_name: spring_app
    restart: always
    working_dir: /app
    volumes:
      - .:/app  # Mount thư mục code vào container
    ports:
      - "8080:8080"
    command: ["./mvnw", "spring-boot:run"]  # Chạy trực tiếp Spring Boot từ source code
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
