version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  app:
    image: openjdk:21-jdk-slim
    container_name: spring_app
    restart: always
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    command: ["/bin/sh", "-c", "cd /app && ./mvnw spring-boot:run"]
    depends_on:
      mysql:
        condition: service_healthy
      otel-collector:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://otel-collector:4318/v1/metrics
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
    networks:
      - app-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    restart: always
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-config/config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"  # Exposed to host (no conflict)
      - "4318:4318"  # Exposed to host (no conflict)
      - "8889:8889"  # Prometheus exporter
      - "8888:8888"  # Collector's own metrics
    depends_on:
      - tempo
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native-histograms"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=supersecurepassword
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"  # Tempo UI on host (no conflict)
      - "50051:4317"  # Host port changed, internal still 4317 (OTLP gRPC)
      - "50052:4318"  # Host port changed, internal still 4318 (OTLP HTTP)
    networks:
      - app-network
    user: "0"

  app_1:
    image: openjdk:21-jdk-slim
    container_name: spring-app-1
    restart: always
    working_dir: /app1
    volumes:
      - ./app1:/app1
      - ./app1/logs:/app1/logs
    ports:
      - "8081:8081"  # Different port from main app
    command: ["/bin/sh", "-c", "cd /app1 && ./mvnw spring-boot:run"]
    depends_on:
      mysql:
        condition: service_healthy
      otel-collector:
        condition: service_started
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://otel-collector:4318/v1/metrics
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mysql_data:
  grafana_data:
  tempo_data: