version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s

  eureka:
    image: openjdk:21-jdk-slim  # Chạy trực tiếp với JDK, không cần build image
    container_name: eureka_server
    working_dir: /app
    volumes:
      - ./eureka:/app  # Mount thư mục code vào containervolumes:
      - ~/.m2:/root/.m2  # Mount thư mục Maven local repository từ host vào container
    ports:
      - "8762:8762"
    networks:
        - app-network
    command: [ "./mvnw", "spring-boot:run" ]  # Chạy trực tiếp Spring Boot từ source code
    environment:
      SERVER_PORT: 8762
      SPRING_APPLICATION_NAME: eureka server
      EUREKA_SERVER_URL: http://eureka:8762/eureka/

  grpcserver:
    image: openjdk:21-jdk-slim
    container_name: spring-app-4
#    restart: always
    working_dir: /app4
    volumes:
      - ./app4:/app4
      - ./app4/logs:/app4/logs
      - ./opentelemetry-javaagent.jar:/app4/opentelemetry-javaagent.jar
      - ~/.m2:/root/.m2
    ports:
      - "8085:8085"  # Different port from main app
      - "9091:9091"
    command: [ "/bin/sh", "-c", "cd /app4 && ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments='-javaagent:/app4/opentelemetry-javaagent.jar'" ]
    depends_on:
      postgres:
        condition: service_healthy
      otel-collector:
        condition: service_started
    environment:
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: POSTGRES_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://otel-collector:4318/v1/metrics
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: my-demo-app-4
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none
      SPRING_APPLICATION_NAME: DEMO-SPRING-BOOT-GRPC
      GRPC_SERVER_PORT: 9091
      EUREKA_SERVER_DEFAULT_ZONE: http://eureka:8762/eureka/
      EUREKA_SERVER_HOSTNAME: grpcserver
    networks:
      - app-network

  app:
    image: openjdk:21-jdk-slim
    container_name: spring_app
#    restart: always
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: ["/bin/sh", "-c", "cd /app && ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments='-javaagent:/app/opentelemetry-javaagent.jar'"]
    depends_on:
      mysql:
        condition: service_healthy
      otel-collector:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://otel-collector:4318/v1/metrics
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      OTEL_SERVICE_NAME: my-demo-app
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none

      SPRING_APPLICATION_NAME: demo-spring-boot
      EUREKA_SERVER_DEFAULT_ZONE: http://eureka:8762/eureka/
      EUREKA_SERVER_HOSTNAME: app
      MCS_NAME_GRPC_SERVER: DEMO-SPRING-BOOT-GRPC
    networks:
      - app-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    restart: always
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-config/config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"  # Exposed to host (no conflict)
      - "4318:4318"  # Exposed to host (no conflict)
      - "8889:8889"  # Prometheus exporter
      - "8888:8888"  # Collector's own metrics
    depends_on:
      - tempo
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native-histograms"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=supersecurepassword
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"  # Tempo UI on host (no conflict)
      - "50051:4317"  # Host port changed, internal still 4317 (OTLP gRPC)
      - "50052:4318"  # Host port changed, internal still 4318 (OTLP HTTP)
    networks:
      - app-network
    user: "0"

  app_1:
    image: openjdk:21-jdk-slim
    container_name: spring-app-1
    restart: always
    working_dir: /app1
    volumes:
      - ./app1:/app1
      - ./app1/logs:/app1/logs
      - ./opentelemetry-javaagent.jar:/app1/opentelemetry-javaagent.jar
    ports:
      - "8081:8081"  # Different port from main app
    command: ["/bin/sh", "-c", "cd /app1 && ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments='-javaagent:/app1/opentelemetry-javaagent.jar'"]
    depends_on:
      mysql:
        condition: service_healthy
      otel-collector:
        condition: service_started
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://otel-collector:4318/v1/metrics
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: my-demo-app-1
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none
    networks:
      - app-network

  app_2:
    image: openjdk:21-jdk-slim
    container_name: spring-app-2
    restart: always
    working_dir: /app2
    volumes:
      - ./app1:/app1
      - ./app1/logs:/app1/logs
      - ./opentelemetry-javaagent.jar:/app1/opentelemetry-javaagent.jar
    ports:
      - "8082:8082"  # Different port from main app
    command: [ "/bin/sh", "-c", "cd /app1 && ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments='-javaagent:/app1/opentelemetry-javaagent.jar'" ]
    depends_on:
      mysql:
        condition: service_healthy
      otel-collector:
        condition: service_started
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://otel-collector:4318/v1/metrics
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: my-demo-app-1
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none
    networks:
      - app-network

  app_3:
    image: openjdk:21-jdk-slim
    container_name: spring-app-3
    restart: always
    working_dir: /app3
    volumes:
      - ./app1:/app1
      - ./app1/logs:/app1/logs
      - ./opentelemetry-javaagent.jar:/app1/opentelemetry-javaagent.jar
    ports:
      - "8083:8083"  # Different port from main app
    command: [ "/bin/sh", "-c", "cd /app1 && ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments='-javaagent:/app1/opentelemetry-javaagent.jar'" ]
    depends_on:
      mysql:
        condition: service_healthy
      otel-collector:
        condition: service_started
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://otel-collector:4318/v1/metrics
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: my-demo-app-1
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none
    networks:
      - app-network

  # Add ZooKeeper (required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Add Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Optional Kafka UI for management
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka
    ports:
      - "8084:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mysql_data:
  grafana_data:
  tempo_data:
  postgres_data: