server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  aop:
    auto: true
    proxy-target-class: true
  security:
    ignored:
      - "/api/service/**"  # Bỏ qua xác thực cho các endpoint test
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE}
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME}
    instance-id: ${spring.application.name}:${grpc.server.port}

grpc:
  server:
    port: 50051  # Port cho gRPC Server
  client:
    mcs_product_grpc_server:
      address: ${MCS_PRODUCT_GRPC_SERVER}
      negotiationType: plaintext
    mcs_order_grpc_server:
      address: ${MCS_ORDER_GRPC_SERVER}
      negotiationType: plaintext
logging:
  level:
    com.example.demo: DEBUG
    org.springframework.web: INFO
#  file:
#    path: logs/

logbook:
  format.style: http
  obfuscate:
    headers:
      - Authorization
      - X-API-Key
    parameters:
      - password
      - secret
      - creditCard
      - cardNumber
  write:
    chunk-size: 1000

resilience4j:  # Cấu hình circuit breaker
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true  # Đăng ký health indicator để monitoring
    instances:
      example:  # Cấu hình cho instance "example" được sử dụng trong TestController
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      example:
        maxAttempts: 3
        waitDuration: 1s
  bulkhead:
    instances:
      example:
        maxConcurrentCalls: 10
  timelimiter:
    instances:
      example:
        timeoutDuration: 2s
  ratelimiter:
    instances:
      example:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
