server:
  port: 8080

spring:
  application:
    name: demo-spring-boot
    instance_id: instance-1
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
    show-sql: true
  aop:
    auto: true
    proxy-target-class: true
  cloud:
    discovery:
      enabled: true

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.web: INFO
#  file:
#    path: logs/

logbook:
  format.style: http
  obfuscate:
    headers:
      - Authorization
      - X-API-Key
    parameters:
      - password
      - secret
      - creditCard
      - cardNumber
  write:
    chunk-size: 1000

grpc:
  client:
    account-service:
      address: 'discovery:///account-service'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    #      default-load-balancing-policy: "round_robin"

    transaction-service:
      address: 'discovery:///transaction-service'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    #      default-load-balancing-policy: "round_robin"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    lease-renewal-interval-in-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}