server:
  port: 8080

#spring:
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
    username: root
    password: MYSQL_ROOT_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

