global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Scrape the OpenTelemetry Collector's metrics endpoint
  - job_name: 'otel-collector'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8889']
    honor_labels: true

  # Scrape OpenTelemetry Collector's own metrics
  - job_name: 'otel-collector-internal'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8888']

  # Scrape the Spring Boot application directly
  - job_name: 'spring-boot'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
