server:
  port: 8080

spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  server:
    enableSelfPreservation: false
