CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    quantity    INTEGER                                 NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);
